# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - main

pool:
  name: Qline-automation-10.0.0.65

jobs:
- job: SetupMavenDependencies
  timeoutInMinutes: 0
  steps:
  - script: mvn dependency:resolve
    displayName: "Resolve Maven Dependencies Without Maven Task"

  - script: mvn dependency:copy-dependencies -DoutputDirectory=target/dependency
    displayName: "Copy Dependencies to Target Directory"

- job: RunTestNGTests
  dependsOn: SetupMavenDependencies
  timeoutInMinutes: 0
  steps:
  - script: java -cp "target/dependency/*:target/classes" org.testng.TestNG testng.xml
    displayName: "Run TestNG Tests Without Maven"


# jobs:
# - job: SetupMaven
#   timeoutInMinutes: 0
#   steps:
#   - task: Maven@2
#     inputs:
#       mavenPomFile: 'pom.xml'
#       goals: 'dependency:resolve'
#     displayName: "Download Maven Dependencies"
    

#schedules:
#- cron: "0 16 * * *"
#  displayName: Daily midnight build
#  branches:
#    include:
#    - main

# jobs:
# - job: RunTests
#   timeoutInMinutes: 0
#   steps:
# #  - checkout: none 
#   - task: Maven@3
#     inputs:
#       mavenPomFile: 'pom.xml'
#       goals: 'test -Dtest=TC_LoginPage'
#    continueOnError: true

  # - task: PublishBuildArtifacts@1
  #   condition: failed()
  #   displayName: 'publish Screenshots as Artifact'
  #   inputs:         
  #     PathtoPublish: 'C:\vsts-agent-win-x64-3.220.5\_work\1\s\Screens\screenshots_TestCasesFail'
  #     ArtifactName: screenshots-$(Relese name)



# # This job creates a work item
# - job: ErrorHandler
#   dependsOn: RunTests
#   condition: failed()
#   steps:
#   - task: CreateWorkItem@2
#     inputs:
#       workItemType: 'Bug'
#       title: 'Please Check the Result '
#       assignedTo: 'Marwan Khalil'
#       areaPath: 'qManagement\qCMS'
#       iterationPath: 'qManagement\2025'
#       fieldMappings: 'qline1=Makeen'
#       associate: true
#       authType: 'internal'





