trigger:
  - main

pool:
  name:  PUB-QCMS


#schedules:
#- cron: "0 16 * * *"
#  displayName: Daily midnight build
#  branches:
#    include:
#    - main

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

jobs:
- job: RunTests
  timeoutInMinutes: 0
  steps:
#  - checkout: none 
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'test -Dtest=TC_LoginPage'
#    continueOnError: true

  - task: PublishBuildArtifacts@1
    condition: failed()
    displayName: 'publish Screenshots as Artifact'
    inputs:         
      PathtoPublish: 'C:/Users/Ahmed.Haraz/Desktop/vsts-agent-win-x64-3.238.0/_work/1/s/screenshots_TestCasesFail'
      ArtifactName: screenshots-$(Relese name)

# This job creates a work item
- job: ErrorHandler
  dependsOn: RunTests
  condition: failed()
  steps:
  - task: CreateWorkItem@2
    inputs:
      workItemType: 'Bug'
      teamProject: 'Makeen_Management'
      title: 'Please Check the Result '
      assignedTo: 'Hagar El Said'
      areaPath: 'Makeen_Management'
      iterationPath: 'Makeen_Management'
      associate: true
      authType: 'internal'
